export default {
  tableDate: [
    {
      deviceName: '华为mate20',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '麒麟',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 2999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '华为mate30',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '麒麟',
      battery: 6000,
      pixel: '3000万',
      storage: '64g',
      fifth: false,
      price: 3999,
      saleTime: '2019-1-1'
    },
    {
      deviceName: '三星Galay Note7',
      deviceType: '手机',
      photoNumber: 2,
      cpu: '高通',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 2999,
      saleTime: '2017-3-9'
    },
    {
      deviceName: 'VIVO X5',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '高通',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 1999,
      saleTime: '2017-9-9'
    },
    {
      deviceName: '苹果 Iphone5S',
      deviceType: '手机',
      photoNumber: 3,
      cpu: 'Apple',
      battery: 5000,
      pixel: '800万',
      storage: '64g',
      fifth: false,
      price: 4999,
      saleTime: '2014-9-12'
    },
    {
      deviceName: '小米5',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '高通',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 1899,
      saleTime: '2017-6-1'
    },
    {
      deviceName: '苹果 Ipad 4',
      deviceType: '平板',
      photoNumber: 1,
      cpu: 'Apple',
      battery: 5000,
      pixel: '800万',
      storage: '64g',
      fifth: false,
      price: 3999,
      saleTime: '2015-9-2'
    },
    {
      deviceName: '华为Pad',
      deviceType: '平板',
      photoNumber: 1,
      cpu: '高通',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 2999,
      saleTime: '2016-9-9'
    },
    {
      deviceName: 'JD Pad',
      deviceType: '平板',
      photoNumber: 1,
      cpu: '高通',
      battery: 5000,
      pixel: '1200万',
      storage: '64g',
      fifth: false,
      price: 999,
      saleTime: '2018-3-1'
    },
    {
      deviceName: '小米笔记本',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: '英特尔',
      battery: 8000,
      pixel: '800万',
      storage: '256g',
      fifth: false,
      price: 4999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '华为matebook',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: 'AMD',
      battery: 5000,
      pixel: '1200万',
      storage: '512g',
      fifth: false,
      price: 5999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '荣耀X5',
      deviceType: '手机',
      photoNumber: 2,
      cpu: '麒麟',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '魅族M5',
      deviceType: '手机',
      photoNumber: 2,
      cpu: '联发科',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 1999,
      saleTime: '2015-9-9'
    },
    {
      deviceName: '联想ThinkPad',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: '英特尔',
      battery: 5000,
      pixel: '800万',
      storage: '512g',
      fifth: false,
      price: 6999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '联想小新5',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: '英特尔',
      battery: 5000,
      pixel: '1200万',
      storage: '256g',
      fifth: false,
      price: 5999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '华为mate40',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '麒麟',
      battery: 5000,
      pixel: '5000万',
      storage: '128g',
      fifth: false,
      price: 8999,
      saleTime: '2020-9-9'
    },
    {
      deviceName: 'MacBook Pro',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: '英特尔',
      battery: 6000,
      pixel: '1200万',
      storage: '512g',
      fifth: false,
      price: 17999,
      saleTime: '2020-3-1'
    },
    {
      deviceName: 'MacBook Air',
      deviceType: '电脑',
      photoNumber: 1,
      cpu: '英特尔',
      battery: 6000,
      pixel: '1200万',
      storage: '256g',
      fifth: false,
      price: 8999,
      saleTime: '2019-9-9'
    },
    {
      deviceName: '苹果 Iphone 8Plus',
      deviceType: '手机',
      photoNumber: 2,
      cpu: 'Apple',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 7999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '苹果 Iphone X',
      deviceType: '手机',
      photoNumber: 3,
      cpu: 'Apple',
      battery: 5000,
      pixel: '2000万',
      storage: '64g',
      fifth: false,
      price: 8999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '苹果 Iphone 11',
      deviceType: '手机',
      photoNumber: 3,
      cpu: 'Apple',
      battery: 5000,
      pixel: '3000万',
      storage: '64g',
      fifth: false,
      price: 9999,
      saleTime: '2019-9-9'
    },
    {
      deviceName: '华为mate50',
      deviceType: '手机',
      photoNumber: 4,
      cpu: '麒麟',
      battery: 5000,
      pixel: '8000万',
      storage: '512g',
      fifth: true,
      price: 10999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '苹果 Iphone 12',
      deviceType: '手机',
      photoNumber: 4,
      cpu: 'Apple',
      battery: 5000,
      pixel: '5000万',
      storage: '512g',
      fifth: true,
      price: 9999,
      saleTime: '2020-9-9'
    },
    {
      deviceName: '华为P20',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '麒麟',
      battery: 5000,
      pixel: '4000万',
      storage: '64g',
      fifth: false,
      price: 5999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '华为P30',
      deviceType: '手机',
      photoNumber: 3,
      cpu: '麒麟',
      battery: 5000,
      pixel: '6000万',
      storage: '64g',
      fifth: false,
      price: 6999,
      saleTime: '2018-9-9'
    },
    {
      deviceName: '华为P50',
      deviceType: '手机',
      photoNumber: 4,
      cpu: '麒麟',
      battery: 5000,
      pixel: '9000万',
      storage: '512',
      fifth: true,
      price: 12999,
      saleTime: '2018-9-9'
    },
  ],
  options: [
    {
      value: '手机',
      label: '手机',
    },
    {
      value: '平板',
      label: '平板',
    },
    {
      value: '电脑',
      label: '电脑',
    }
  ]
}
